---
version: "3"

services:
  flask_server:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./app.db:/app/app.db
    depends_on:
      clickhouse:
        condition: service_healthy
  clickhouse:
    image: clickhouse/clickhouse-server:23.4.2
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    environment:
      # Default user and database will be created using `init-defaults.sh` script
      CLICKHOUSE_DB: metrics
      CLICKHOUSE_USER: monitor_clk
      CLICKHOUSE_PASSWORD: 239QVRVlfsvtfd
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse/init-defaults.sh:/docker-entrypoint-initdb.d/init-defaults.sh:ro
      - ./clickhouse/users.d:/etc/clickhouse-server/users.d
      - ./clickhouse-data:/var/lib/clickhouse/
      - ./clickhouse-logs:/var/log/clickhouse-server/